import { scoreStock } from "@/lib/scoring";
import type {
  BacktestSummary,
  EmergingNarrative,
  MarketState,
  NewsItem,
  PennyStockSignal,
  PricePoint,
  RawStockSignal,
  SectorSignal,
  SpeculativeSignal,
  SupplyChainLink,
} from "@/lib/types";

const history = (base: number, drift: number, volatility: number): PricePoint[] =>
  Array.from({ length: 42 }, (_, index) => {
    const wave = Math.sin(index / 3.4) * volatility + Math.cos(index / 6) * volatility * 0.6;
    const close = Number((base + index * drift + wave).toFixed(2));
    const date = new Date(Date.UTC(2026, 3, 1 + index)).toISOString().slice(0, 10);

    return {
      date,
      close,
      volume: Math.round(1_000_000 + Math.abs(wave) * 180_000 + index * 19_000),
    };
  });

const sourceUrls: Record<string, string> = {
  "Analyst desk": "https://finance.yahoo.com/research-hub/",
  Benzinga: "https://www.benzinga.com/",
  "Energy desk": "https://www.eia.gov/",
  FDA: "https://www.fda.gov/",
  "FDA calendar": "https://www.fda.gov/",
  Finnhub: "https://finnhub.io/",
  MarketWatch: "https://www.marketwatch.com/",
  Reuters: "https://www.reuters.com/markets/",
  SEC: "https://www.sec.gov/edgar/search/",
};

const news = (
  symbol: string,
  source: string,
  sentiment: NewsItem["sentiment"],
  title: string,
  summary: string
): NewsItem => ({
  id: `${symbol}-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
  symbol,
  title,
  source,
  url: sourceUrls[source] || "https://finance.yahoo.com/news/",
  sentiment,
  relevance: sentiment === "neutral" ? 62 : 78,
  publishedAt: "2026-05-16T13:20:00.000Z",
  summary,
});

export const marketState: MarketState = {
  regime: "Risk-On",
  mood: "Constructive but not complacent",
  fearGreed: 58,
  fearGreedLabel: "Greed",
  vix: 17.8,
  breadth: 64,
  trendScore: 69,
  macroRisk: 44,
  mostBullishSector: "Semiconductors",
  mostBearishSector: "Consumer Retail",
  updatedAt: "2026-05-16T14:30:00.000Z",
  drivers: [
    "Large-cap earnings revisions are positive.",
    "Credit stress is contained, but rate sensitivity remains relevant.",
    "Market breadth is healthy enough to support selective momentum.",
  ],
  risks: [
    "High-valuation growth names remain sensitive to bond yields.",
    "Geopolitical headline risk can change intraday sentiment quickly.",
    "Crowded AI narratives require stronger evidence before confidence rises.",
  ],
};

export const sectors: SectorSignal[] = [
  { sector: "Semiconductors", relativeStrength: 86, sentiment: 78, flow: 82, label: "Leadership" },
  { sector: "Healthcare", relativeStrength: 73, sentiment: 68, flow: 66, label: "Defensive bid" },
  { sector: "Energy", relativeStrength: 70, sentiment: 61, flow: 74, label: "Macro tailwind" },
  { sector: "Financials", relativeStrength: 62, sentiment: 55, flow: 58, label: "Rate watch" },
  { sector: "Software", relativeStrength: 59, sentiment: 71, flow: 52, label: "Selective" },
  { sector: "Consumer Staples", relativeStrength: 53, sentiment: 49, flow: 60, label: "Stable" },
  { sector: "Industrials", relativeStrength: 50, sentiment: 52, flow: 47, label: "Sideways" },
  { sector: "Consumer Retail", relativeStrength: 38, sentiment: 35, flow: 31, label: "Weak breadth" },
];

export const rawStocks: RawStockSignal[] = [
  {
    symbol: "NVDA",
    name: "NVIDIA",
    sector: "Semiconductors",
    industry: "Accelerated computing",
    marketCap: 3_150_000_000_000,
    price: 132.45,
    changePercent: 1.8,
    metrics: {
      revenueGrowth: 74,
      profitMargin: 56,
      freeCashFlowMargin: 47,
      debtToEquity: 0.25,
      pe: 47,
      forwardPe: 31,
      peg: 1.3,
      priceToSales: 18,
      roe: 72,
      moat: 94,
      consistency: 88,
      epsGrowth: 82,
      earningsSurprise: 78,
      guidanceScore: 86,
      volatility: 48,
      beta: 1.65,
      negativeNewsRisk: 39,
      momentum30d: 82,
      aboveMovingAverages: 91,
      rsiQuality: 68,
      volumeSpike: 72,
      newsSentimentScore: 79,
      breakoutQuality: 76,
      supportQuality: 64,
      stopLossDistance: 9,
      institutionalFlow: 84,
      insiderSignal: 52,
      dataCompleteness: 94,
      sourceAgreement: 83,
    },
    priceHistory: history(116, 0.38, 3.8),
    news: [
      news("NVDA", "Benzinga", "positive", "AI infrastructure demand remains resilient", "Analysts continue to cite data center demand and supply visibility."),
      news("NVDA", "SEC", "neutral", "Quarterly filing highlights export-control risk", "Management flags geopolitical and regulatory risk in core markets."),
    ],
    upcomingDates: ["Earnings window: late May", "Investor conference: June 2026"],
    sourceLinks: [
      { label: "SEC filings", url: "https://www.sec.gov/edgar/search/", reliability: "primary" },
      { label: "Financial Modeling Prep", url: "https://financialmodelingprep.com/", reliability: "licensed" },
    ],
  },
  {
    symbol: "MSFT",
    name: "Microsoft",
    sector: "Software",
    industry: "Cloud platforms",
    marketCap: 3_000_000_000_000,
    price: 431.2,
    changePercent: 0.7,
    dividendYield: 0.7,
    metrics: {
      revenueGrowth: 17,
      profitMargin: 36,
      freeCashFlowMargin: 33,
      debtToEquity: 0.36,
      pe: 34,
      forwardPe: 29,
      peg: 2.1,
      priceToSales: 12,
      roe: 39,
      moat: 91,
      consistency: 92,
      epsGrowth: 21,
      earningsSurprise: 66,
      guidanceScore: 74,
      volatility: 26,
      beta: 0.93,
      negativeNewsRisk: 23,
      momentum30d: 68,
      aboveMovingAverages: 76,
      rsiQuality: 69,
      volumeSpike: 51,
      newsSentimentScore: 72,
      breakoutQuality: 62,
      supportQuality: 76,
      stopLossDistance: 6,
      institutionalFlow: 74,
      insiderSignal: 47,
      dataCompleteness: 96,
      sourceAgreement: 88,
    },
    priceHistory: history(402, 0.55, 5.1),
    news: [
      news("MSFT", "Finnhub", "positive", "Cloud margins stay in focus", "Investors are watching AI infrastructure spending against Azure growth."),
      news("MSFT", "SEC", "neutral", "Capital expenditure commitments rise", "Long-duration AI infrastructure spending remains a key risk variable."),
    ],
    upcomingDates: ["Dividend date: June", "Cloud product event: June 2026"],
    sourceLinks: [
      { label: "SEC filings", url: "https://www.sec.gov/edgar/search/", reliability: "primary" },
      { label: "Alpha Vantage", url: "https://www.alphavantage.co/", reliability: "licensed" },
    ],
  },
  {
    symbol: "LLY",
    name: "Eli Lilly",
    sector: "Healthcare",
    industry: "Pharmaceuticals",
    marketCap: 810_000_000_000,
    price: 842.1,
    changePercent: 1.1,
    metrics: {
      revenueGrowth: 28,
      profitMargin: 24,
      freeCashFlowMargin: 19,
      debtToEquity: 1.35,
      pe: 61,
      forwardPe: 42,
      peg: 1.9,
      priceToSales: 18,
      roe: 58,
      moat: 88,
      consistency: 79,
      epsGrowth: 44,
      earningsSurprise: 72,
      guidanceScore: 82,
      volatility: 34,
      beta: 0.64,
      negativeNewsRisk: 31,
      momentum30d: 71,
      aboveMovingAverages: 78,
      rsiQuality: 62,
      volumeSpike: 67,
      newsSentimentScore: 75,
      breakoutQuality: 69,
      supportQuality: 71,
      stopLossDistance: 8,
      institutionalFlow: 78,
      insiderSignal: 50,
      dataCompleteness: 91,
      sourceAgreement: 81,
    },
    priceHistory: history(776, 1.35, 13),
    news: [
      news("LLY", "MarketWatch", "positive", "Obesity-drug demand remains a growth driver", "Supply expansion and prescription trends support the long-term thesis."),
      news("LLY", "FDA calendar", "neutral", "Pipeline catalysts create event risk", "Upcoming readouts can widen expected move ranges."),
    ],
    upcomingDates: ["FDA calendar: Q3", "Earnings window: early August"],
    sourceLinks: [
      { label: "SEC filings", url: "https://www.sec.gov/edgar/search/", reliability: "primary" },
      { label: "FRED macro series", url: "https://fred.stlouisfed.org/", reliability: "primary" },
    ],
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase",
    sector: "Financials",
    industry: "Money center banks",
    marketCap: 560_000_000_000,
    price: 203.8,
    changePercent: -0.3,
    dividendYield: 2.1,
    metrics: {
      revenueGrowth: 9,
      profitMargin: 31,
      freeCashFlowMargin: 27,
      debtToEquity: 1.7,
      pe: 13,
      forwardPe: 12,
      peg: 1.4,
      priceToSales: 3.4,
      roe: 17,
      moat: 82,
      consistency: 84,
      epsGrowth: 12,
      earningsSurprise: 60,
      guidanceScore: 62,
      volatility: 24,
      beta: 1.08,
      negativeNewsRisk: 34,
      momentum30d: 56,
      aboveMovingAverages: 61,
      rsiQuality: 65,
      volumeSpike: 45,
      newsSentimentScore: 58,
      breakoutQuality: 48,
      supportQuality: 69,
      stopLossDistance: 5,
      institutionalFlow: 65,
      insiderSignal: 55,
      dataCompleteness: 93,
      sourceAgreement: 78,
    },
    priceHistory: history(195, 0.19, 2.8),
    news: [
      news("JPM", "Reuters", "neutral", "Net interest income remains rate sensitive", "Bank quality is solid, but macro sensitivity drives the setup."),
      news("JPM", "SEC", "neutral", "Credit-loss language stays contained", "Credit quality requires monitoring if unemployment trends weaken."),
    ],
    upcomingDates: ["Stress test results: June", "Dividend update: Q3"],
    sourceLinks: [
      { label: "SEC filings", url: "https://www.sec.gov/edgar/search/", reliability: "primary" },
      { label: "FRED rates", url: "https://fred.stlouisfed.org/", reliability: "primary" },
    ],
  },
  {
    symbol: "XOM",
    name: "Exxon Mobil",
    sector: "Energy",
    industry: "Integrated oil and gas",
    marketCap: 515_000_000_000,
    price: 118.5,
    changePercent: 0.5,
    dividendYield: 3.2,
    metrics: {
      revenueGrowth: 7,
      profitMargin: 11,
      freeCashFlowMargin: 14,
      debtToEquity: 0.21,
      pe: 14,
      forwardPe: 13,
      peg: 1.1,
      priceToSales: 1.4,
      roe: 18,
      moat: 76,
      consistency: 68,
      epsGrowth: 9,
      earningsSurprise: 56,
      guidanceScore: 59,
      volatility: 29,
      beta: 0.98,
      negativeNewsRisk: 41,
      momentum30d: 65,
      aboveMovingAverages: 70,
      rsiQuality: 64,
      volumeSpike: 62,
      newsSentimentScore: 54,
      breakoutQuality: 58,
      supportQuality: 67,
      stopLossDistance: 7,
      institutionalFlow: 69,
      insiderSignal: 58,
      dataCompleteness: 90,
      sourceAgreement: 76,
    },
    priceHistory: history(111, 0.18, 2.4),
    news: [
      news("XOM", "Energy desk", "neutral", "Oil risk premium supports energy flows", "Geopolitical risk and supply discipline are driving sector interest."),
      news("XOM", "SEC", "negative", "Commodity exposure keeps earnings cyclical", "Cash flow remains tied to oil and refining margins."),
    ],
    upcomingDates: ["OPEC meeting: June", "Earnings window: late July"],
    sourceLinks: [
      { label: "SEC filings", url: "https://www.sec.gov/edgar/search/", reliability: "primary" },
      { label: "EIA data", url: "https://www.eia.gov/", reliability: "primary" },
    ],
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices",
    sector: "Semiconductors",
    industry: "Data center chips",
    marketCap: 260_000_000_000,
    price: 158.7,
    changePercent: 2.4,
    metrics: {
      revenueGrowth: 23,
      profitMargin: 7,
      freeCashFlowMargin: 13,
      debtToEquity: 0.05,
      pe: 52,
      forwardPe: 28,
      peg: 1.6,
      priceToSales: 9,
      roe: 7,
      moat: 71,
      consistency: 58,
      epsGrowth: 34,
      earningsSurprise: 61,
      guidanceScore: 70,
      volatility: 57,
      beta: 1.82,
      negativeNewsRisk: 45,
      momentum30d: 76,
      aboveMovingAverages: 82,
      rsiQuality: 60,
      volumeSpike: 84,
      newsSentimentScore: 69,
      breakoutQuality: 81,
      supportQuality: 53,
      stopLossDistance: 13,
      institutionalFlow: 71,
      insiderSignal: 45,
      dataCompleteness: 87,
      sourceAgreement: 72,
    },
    priceHistory: history(136, 0.5, 6.6),
    news: [
      news("AMD", "Benzinga", "positive", "AI chip share narrative strengthens", "Momentum improved after data center commentary and volume expansion."),
      news("AMD", "Analyst desk", "neutral", "Competition risk remains central", "Investors still compare gross margins and ecosystem strength against peers."),
    ],
    upcomingDates: ["Product event: June", "Earnings window: July"],
    sourceLinks: [
      { label: "SEC filings", url: "https://www.sec.gov/edgar/search/", reliability: "primary" },
      { label: "Polygon", url: "https://polygon.io/", reliability: "licensed" },
    ],
  },
];

const popularSymbols = [
  "AAPL",
  "MSFT",
  "NVDA",
  "AMZN",
  "GOOGL",
  "META",
  "TSLA",
  "AMD",
  "AVGO",
  "ASML",
  "TSM",
  "MU",
  "QCOM",
  "INTC",
  "AMAT",
  "LRCX",
  "KLAC",
  "ARM",
  "MRVL",
  "SMCI",
  "PLTR",
  "CRWD",
  "PANW",
  "NET",
  "SNOW",
  "DDOG",
  "MDB",
  "NOW",
  "CRM",
  "ADBE",
  "ORCL",
  "IBM",
  "CSCO",
  "ANET",
  "SHOP",
  "UBER",
  "ABNB",
  "DASH",
  "ROKU",
  "RBLX",
  "JPM",
  "BAC",
  "WFC",
  "GS",
  "MS",
  "V",
  "MA",
  "PYPL",
  "SQ",
  "COIN",
  "LLY",
  "UNH",
  "JNJ",
  "ABBV",
  "MRK",
  "PFE",
  "TMO",
  "ISRG",
  "VRTX",
  "REGN",
  "XOM",
  "CVX",
  "COP",
  "SLB",
  "OXY",
  "NEE",
  "DUK",
  "SO",
  "CEG",
  "NUE",
  "VRT",
  "WMT",
  "COST",
  "HD",
  "LOW",
  "TGT",
  "NKE",
  "SBUX",
  "MCD",
  "KO",
  "PEP",
  "PG",
  "CL",
  "EL",
  "DIS",
  "NFLX",
  "CMCSA",
  "T",
  "VZ",
  "TMUS",
  "SPOT",
  "BA",
  "GE",
  "CAT",
  "DE",
  "HON",
  "RTX",
  "LMT",
  "NOC",
  "GD",
  "UPS",
  "FDX",
  "DAL",
  "UAL",
  "AAL",
  "GM",
  "F",
  "RIVN",
  "LCID",
  "NIO",
  "LI",
  "BABA",
  "JD",
  "PDD",
  "SE",
  "MELI",
  "SONY",
  "TM",
  "HMC",
  "SAP",
  "RACE",
  "UL",
  "RIO",
  "BHP",
  "VALE",
  "GOLD",
  "NEM",
  "FCX",
  "AA",
  "ALB",
  "ENPH",
  "FSLR",
  "SEDG",
  "RUN",
  "PLUG",
  "BE",
  "QS",
  "IONQ",
  "RGTI",
  "QBTS",
  "SOUN",
  "AI",
  "BBAI",
  "PATH",
  "U",
  "HOOD",
  "AFRM",
  "SOFI",
  "UPST",
  "TOST",
  "ETSY",
  "EBAY",
  "BKNG",
  "EXPE",
  "MAR",
  "HLT",
  "LULU",
  "ELF",
  "CELH",
  "MNST",
  "AXP",
  "BLK",
  "SCHW",
  "C",
  "USB",
  "PNC",
  "TFC",
  "CB",
  "AIG",
  "BRK-B",
  "SPY",
  "QQQ",
  "DIA",
  "IWM",
  "XLK",
  "XLF",
  "XLE",
  "XLV",
  "SMH",
  "SOXX",
  "ARKK",
  "VTI",
  "VOO",
  "VEA",
  "VWO",
  "TLT",
  "HYG",
  "GLD",
  "SLV",
  "USO",
  "BTC-USD",
  "ETH-USD",
  "SOL-USD",
  "DOGE-USD",
  "XRP-USD",
  "ADA-USD",
  "AVAX-USD",
  "LINK-USD",
  "MATIC-USD",
  "DOT-USD",
];

const companyNames: Record<string, string> = {
  AAPL: "Apple",
  MSFT: "Microsoft",
  NVDA: "NVIDIA",
  AMZN: "Amazon",
  GOOGL: "Alphabet",
  META: "Meta Platforms",
  TSLA: "Tesla",
  AMD: "Advanced Micro Devices",
  AVGO: "Broadcom",
  ASML: "ASML",
  TSM: "Taiwan Semiconductor",
  MU: "Micron",
  QCOM: "Qualcomm",
  INTC: "Intel",
  AMAT: "Applied Materials",
  LRCX: "Lam Research",
  KLAC: "KLA",
  ARM: "Arm Holdings",
  MRVL: "Marvell",
  SMCI: "Super Micro Computer",
  PLTR: "Palantir Technologies",
  CRWD: "CrowdStrike",
  PANW: "Palo Alto Networks",
  NET: "Cloudflare",
  SNOW: "Snowflake",
  DDOG: "Datadog",
  MDB: "MongoDB",
  NOW: "ServiceNow",
  CRM: "Salesforce",
  ADBE: "Adobe",
  ORCL: "Oracle",
  IBM: "IBM",
  CSCO: "Cisco",
  ANET: "Arista Networks",
  SHOP: "Shopify",
  UBER: "Uber",
  ABNB: "Airbnb",
  DASH: "DoorDash",
  ROKU: "Roku",
  RBLX: "Roblox",
  BAC: "Bank of America",
  WFC: "Wells Fargo",
  GS: "Goldman Sachs",
  MS: "Morgan Stanley",
  V: "Visa",
  MA: "Mastercard",
  PYPL: "PayPal",
  SQ: "Block",
  COIN: "Coinbase",
  UNH: "UnitedHealth",
  JNJ: "Johnson & Johnson",
  ABBV: "AbbVie",
  MRK: "Merck",
  PFE: "Pfizer",
  TMO: "Thermo Fisher",
  ISRG: "Intuitive Surgical",
  VRTX: "Vertex Pharmaceuticals",
  REGN: "Regeneron",
  CVX: "Chevron",
  COP: "ConocoPhillips",
  SLB: "Schlumberger",
  OXY: "Occidental Petroleum",
  NEE: "NextEra Energy",
  DUK: "Duke Energy",
  SO: "Southern Company",
  CEG: "Constellation Energy",
  NUE: "Nucor",
  VRT: "Vertiv",
  WMT: "Walmart",
  COST: "Costco",
  HD: "Home Depot",
  LOW: "Lowe's",
  TGT: "Target",
  NKE: "Nike",
  SBUX: "Starbucks",
  MCD: "McDonald's",
  KO: "Coca-Cola",
  PEP: "PepsiCo",
  PG: "Procter & Gamble",
  CL: "Colgate-Palmolive",
  EL: "Estee Lauder",
  DIS: "Disney",
  NFLX: "Netflix",
  CMCSA: "Comcast",
  T: "AT&T",
  VZ: "Verizon",
  TMUS: "T-Mobile US",
  SPOT: "Spotify",
  BA: "Boeing",
  GE: "GE Aerospace",
  CAT: "Caterpillar",
  DE: "Deere",
  HON: "Honeywell",
  RTX: "RTX",
  LMT: "Lockheed Martin",
  NOC: "Northrop Grumman",
  GD: "General Dynamics",
  UPS: "UPS",
  FDX: "FedEx",
  DAL: "Delta Air Lines",
  UAL: "United Airlines",
  AAL: "American Airlines",
  GM: "General Motors",
  F: "Ford",
  RIVN: "Rivian",
  LCID: "Lucid",
  NIO: "NIO",
  LI: "Li Auto",
  BABA: "Alibaba",
  JD: "JD.com",
  PDD: "PDD Holdings",
  SE: "Sea",
  MELI: "MercadoLibre",
  SONY: "Sony",
  TM: "Toyota",
  HMC: "Honda",
  SAP: "SAP",
  RACE: "Ferrari",
  UL: "Unilever",
  RIO: "Rio Tinto",
  BHP: "BHP",
  VALE: "Vale",
  GOLD: "Barrick Gold",
  NEM: "Newmont",
  FCX: "Freeport-McMoRan",
  AA: "Alcoa",
  ALB: "Albemarle",
  ENPH: "Enphase Energy",
  FSLR: "First Solar",
  SEDG: "SolarEdge",
  RUN: "Sunrun",
  PLUG: "Plug Power",
  BE: "Bloom Energy",
  QS: "QuantumScape",
  IONQ: "IonQ",
  RGTI: "Rigetti Computing",
  QBTS: "D-Wave Quantum",
  SOUN: "SoundHound AI",
  AI: "C3.ai",
  BBAI: "BigBear.ai",
  PATH: "UiPath",
  U: "Unity Software",
  HOOD: "Robinhood",
  AFRM: "Affirm",
  SOFI: "SoFi Technologies",
  UPST: "Upstart",
  TOST: "Toast",
  ETSY: "Etsy",
  EBAY: "eBay",
  BKNG: "Booking Holdings",
  EXPE: "Expedia",
  MAR: "Marriott",
  HLT: "Hilton",
  LULU: "Lululemon",
  ELF: "e.l.f. Beauty",
  CELH: "Celsius Holdings",
  MNST: "Monster Beverage",
  AXP: "American Express",
  BLK: "BlackRock",
  SCHW: "Charles Schwab",
  C: "Citigroup",
  USB: "U.S. Bancorp",
  PNC: "PNC Financial",
  TFC: "Truist Financial",
  CB: "Chubb",
  AIG: "AIG",
  "BRK-B": "Berkshire Hathaway",
  SPY: "SPDR S&P 500 ETF",
  QQQ: "Invesco QQQ Trust",
  DIA: "SPDR Dow Jones Industrial Average ETF",
  IWM: "iShares Russell 2000 ETF",
  XLK: "Technology Select Sector SPDR",
  XLF: "Financial Select Sector SPDR",
  XLE: "Energy Select Sector SPDR",
  XLV: "Health Care Select Sector SPDR",
  SMH: "VanEck Semiconductor ETF",
  SOXX: "iShares Semiconductor ETF",
  ARKK: "ARK Innovation ETF",
  VTI: "Vanguard Total Stock Market ETF",
  VOO: "Vanguard S&P 500 ETF",
  VEA: "Vanguard Developed Markets ETF",
  VWO: "Vanguard Emerging Markets ETF",
  TLT: "iShares 20+ Year Treasury Bond ETF",
  HYG: "iShares High Yield Corporate Bond ETF",
  GLD: "SPDR Gold Shares",
  SLV: "iShares Silver Trust",
  USO: "United States Oil Fund",
  "BTC-USD": "Bitcoin",
  "ETH-USD": "Ethereum",
  "SOL-USD": "Solana",
  "DOGE-USD": "Dogecoin",
  "XRP-USD": "XRP",
  "ADA-USD": "Cardano",
  "AVAX-USD": "Avalanche",
  "LINK-USD": "Chainlink",
  "MATIC-USD": "Polygon",
  "DOT-USD": "Polkadot",
};

const semiconductorSymbols = new Set([
  "NVDA",
  "AMD",
  "AVGO",
  "ASML",
  "TSM",
  "MU",
  "QCOM",
  "INTC",
  "AMAT",
  "LRCX",
  "KLAC",
  "ARM",
  "MRVL",
  "SMCI",
]);

const softwareSymbols = new Set([
  "MSFT",
  "GOOGL",
  "META",
  "PLTR",
  "CRWD",
  "PANW",
  "NET",
  "SNOW",
  "DDOG",
  "MDB",
  "NOW",
  "CRM",
  "ADBE",
  "ORCL",
  "IBM",
  "CSCO",
  "ANET",
  "SHOP",
  "UBER",
  "ABNB",
  "DASH",
  "ROKU",
  "RBLX",
  "SPOT",
  "AI",
  "BBAI",
  "PATH",
  "U",
]);

const financialSymbols = new Set([
  "JPM",
  "BAC",
  "WFC",
  "GS",
  "MS",
  "V",
  "MA",
  "PYPL",
  "SQ",
  "COIN",
  "AXP",
  "BLK",
  "SCHW",
  "C",
  "USB",
  "PNC",
  "TFC",
  "CB",
  "AIG",
  "BRK-B",
  "HOOD",
  "AFRM",
  "SOFI",
  "UPST",
]);

const healthcareSymbols = new Set([
  "LLY",
  "UNH",
  "JNJ",
  "ABBV",
  "MRK",
  "PFE",
  "TMO",
  "ISRG",
  "VRTX",
  "REGN",
]);

const energySymbols = new Set([
  "XOM",
  "CVX",
  "COP",
  "SLB",
  "OXY",
  "NEE",
  "DUK",
  "SO",
  "CEG",
  "VRT",
  "ENPH",
  "FSLR",
  "SEDG",
  "RUN",
  "PLUG",
  "BE",
]);

const industrialSymbols = new Set([
  "BA",
  "GE",
  "CAT",
  "DE",
  "HON",
  "RTX",
  "LMT",
  "NOC",
  "GD",
  "UPS",
  "FDX",
  "DAL",
  "UAL",
  "AAL",
  "GM",
  "F",
  "RIVN",
  "LCID",
  "NIO",
  "LI",
]);

const consumerSymbols = new Set([
  "AAPL",
  "AMZN",
  "TSLA",
  "WMT",
  "COST",
  "HD",
  "LOW",
  "TGT",
  "NKE",
  "SBUX",
  "MCD",
  "KO",
  "PEP",
  "PG",
  "CL",
  "EL",
  "DIS",
  "NFLX",
  "CMCSA",
  "T",
  "VZ",
  "TMUS",
  "ETSY",
  "EBAY",
  "BKNG",
  "EXPE",
  "MAR",
  "HLT",
  "LULU",
  "ELF",
  "CELH",
  "MNST",
]);

const globalSymbols = new Set([
  "BABA",
  "JD",
  "PDD",
  "SE",
  "MELI",
  "SONY",
  "TM",
  "HMC",
  "SAP",
  "RACE",
  "UL",
  "RIO",
  "BHP",
  "VALE",
]);

const commoditySymbols = new Set(["GOLD", "NEM", "FCX", "AA", "ALB"]);
const etfSymbols = new Set([
  "SPY",
  "QQQ",
  "DIA",
  "IWM",
  "XLK",
  "XLF",
  "XLE",
  "XLV",
  "SMH",
  "SOXX",
  "ARKK",
  "VTI",
  "VOO",
  "VEA",
  "VWO",
  "TLT",
  "HYG",
  "GLD",
  "SLV",
  "USO",
]);
const cryptoSymbols = new Set(popularSymbols.filter((symbol) => symbol.endsWith("-USD")));
const speculativeSymbols = new Set([
  "RIVN",
  "LCID",
  "NIO",
  "PLUG",
  "BE",
  "QS",
  "IONQ",
  "RGTI",
  "QBTS",
  "SOUN",
  "AI",
  "BBAI",
  "PATH",
  "U",
  "HOOD",
  "AFRM",
  "SOFI",
  "UPST",
  "TOST",
  "ARKK",
  ...cryptoSymbols,
]);

const sectorForSymbol = (symbol: string) => {
  if (etfSymbols.has(symbol)) return "ETF";
  if (cryptoSymbols.has(symbol)) return "Crypto";
  if (semiconductorSymbols.has(symbol)) return "Semiconductors";
  if (softwareSymbols.has(symbol)) return "Software";
  if (financialSymbols.has(symbol)) return "Financials";
  if (healthcareSymbols.has(symbol)) return "Healthcare";
  if (energySymbols.has(symbol)) return "Energy";
  if (industrialSymbols.has(symbol)) return "Industrials";
  if (consumerSymbols.has(symbol)) return "Consumer";
  if (globalSymbols.has(symbol)) return "Global Equities";
  if (commoditySymbols.has(symbol)) return "Materials";
  return "Cross-Asset";
};

const industryForSector = (sector: string) => {
  switch (sector) {
    case "ETF":
      return "Exchange-traded funds";
    case "Crypto":
      return "Digital assets";
    case "Semiconductors":
      return "AI and semiconductor ecosystem";
    case "Software":
      return "Software and digital platforms";
    case "Financials":
      return "Banking, payments, and financial infrastructure";
    case "Healthcare":
      return "Healthcare and life sciences";
    case "Energy":
      return "Energy, utilities, and power infrastructure";
    case "Industrials":
      return "Industrial, aerospace, logistics, and automation";
    case "Consumer":
      return "Consumer platforms, staples, and discretionary";
    case "Global Equities":
      return "International large-cap equities";
    case "Materials":
      return "Materials and commodities";
    default:
      return "Global research universe";
  }
};

const seedFromSymbol = (symbol: string) =>
  symbol.split("").reduce((total, char) => total + char.charCodeAt(0), 0);

const bounded = (value: number, min: number, max: number) =>
  Math.min(max, Math.max(min, value));

const generatedMarketCap = (symbol: string, sector: string, seed: number) => {
  if (cryptoSymbols.has(symbol)) return (8 + (seed % 75)) * 1_000_000_000;
  if (etfSymbols.has(symbol)) return (12 + (seed % 180)) * 1_000_000_000;
  if (speculativeSymbols.has(symbol)) return (1 + (seed % 60)) * 1_000_000_000;
  if (sector === "Semiconductors" || sector === "Software") return (45 + (seed % 500)) * 1_000_000_000;
  if (sector === "Financials" || sector === "Healthcare" || sector === "Consumer") {
    return (35 + (seed % 420)) * 1_000_000_000;
  }
  return (12 + (seed % 260)) * 1_000_000_000;
};

const generatedPrice = (symbol: string, seed: number, index: number) => {
  if (symbol === "BTC-USD") return 104_500;
  if (symbol === "ETH-USD") return 3_850;
  if (cryptoSymbols.has(symbol)) return Number((0.25 + (seed % 220) / 10).toFixed(2));
  if (speculativeSymbols.has(symbol)) return Number((1.2 + (seed % 140) / 4).toFixed(2));
  return Number((18 + (seed % 360) + (index % 9) * 2.15).toFixed(2));
};

const createGeneratedStock = (symbol: string, index: number): RawStockSignal => {
  const seed = seedFromSymbol(symbol);
  const sector = sectorForSymbol(symbol);
  const isSpeculative = speculativeSymbols.has(symbol);
  const isDefensive = healthcareSymbols.has(symbol) || consumerSymbols.has(symbol) || sector === "ETF";
  const isGrowth = semiconductorSymbols.has(symbol) || softwareSymbols.has(symbol) || cryptoSymbols.has(symbol);
  const price = generatedPrice(symbol, seed, index);
  const marketCap = generatedMarketCap(symbol, sector, seed);
  const qualityBias = isDefensive ? 8 : isGrowth ? 4 : 0;
  const riskBias = isSpeculative ? 22 : cryptoSymbols.has(symbol) ? 28 : sector === "ETF" ? -16 : 0;
  const growthBias = isGrowth ? 18 : isDefensive ? 4 : 7;
  const marginBias = sector === "Software" ? 12 : sector === "Semiconductors" ? 8 : sector === "Energy" ? -4 : 0;
  const volumeSignal = bounded(42 + (seed % 45) + (isSpeculative ? 12 : 0), 22, 96);
  const momentumSignal = bounded(46 + ((seed + index * 3) % 42) + (isGrowth ? 8 : 0), 24, 96);
  const volatility = bounded(24 + (seed % 34) + riskBias, 12, 96);
  const debtToEquity = sector === "Financials" ? 1.4 + (seed % 45) / 30 : bounded((seed % 95) / 70, 0.03, 2.15);

  return {
    symbol,
    name: companyNames[symbol] || symbol,
    sector,
    industry: industryForSector(sector),
    marketCap,
    price,
    changePercent: Number((((seed % 70) - 31) / 10).toFixed(2)),
    dividendYield: isDefensive ? Number(((seed % 36) / 10).toFixed(1)) : undefined,
    metrics: {
      revenueGrowth: bounded(5 + (seed % 34) + growthBias, 2, 86),
      profitMargin: bounded(8 + (seed % 28) + marginBias, 3, 58),
      freeCashFlowMargin: bounded(7 + (seed % 24) + qualityBias, 2, 52),
      debtToEquity,
      pe: bounded(12 + (seed % 48) + (isSpeculative ? 12 : 0), 7, 82),
      forwardPe: bounded(10 + (seed % 34) + (isSpeculative ? 8 : 0), 6, 68),
      peg: Number(bounded(0.8 + (seed % 28) / 10 + (isSpeculative ? 0.5 : 0), 0.6, 4.2).toFixed(1)),
      priceToSales: bounded(1.4 + (seed % 16) + (isGrowth ? 3 : 0), 0.6, 24),
      roe: bounded(10 + (seed % 36) + qualityBias, 2, 76),
      moat: bounded(48 + (seed % 38) + (marketCap > 200_000_000_000 ? 10 : 0), 28, 94),
      consistency: bounded(46 + ((seed + index) % 36) + qualityBias, 26, 94),
      epsGrowth: bounded(8 + (seed % 42) + growthBias, 0, 88),
      earningsSurprise: bounded(46 + (seed % 34) + (isGrowth ? 5 : 0), 24, 88),
      guidanceScore: bounded(45 + ((seed + 7) % 38) + (isGrowth ? 6 : 0), 24, 90),
      volatility,
      beta: Number(bounded(0.7 + (seed % 90) / 100 + (isSpeculative ? 0.45 : 0), 0.45, 2.45).toFixed(2)),
      negativeNewsRisk: bounded(24 + (seed % 38) + (isSpeculative ? 14 : 0), 14, 92),
      momentum30d: momentumSignal,
      aboveMovingAverages: bounded(momentumSignal + ((seed % 16) - 6), 24, 96),
      rsiQuality: bounded(48 + (seed % 32), 25, 86),
      volumeSpike: volumeSignal,
      newsSentimentScore: bounded(48 + ((seed + index) % 38) + (isGrowth ? 4 : 0), 22, 90),
      breakoutQuality: bounded(momentumSignal - 4 + (seed % 12), 22, 94),
      supportQuality: bounded(48 + (seed % 34) + (isDefensive ? 8 : 0), 22, 92),
      stopLossDistance: bounded(5 + (seed % 12) + (isSpeculative ? 3 : 0), 3, 20),
      institutionalFlow: bounded(44 + (seed % 40) + (marketCap > 120_000_000_000 ? 8 : 0), 18, 94),
      insiderSignal: bounded(42 + ((seed + 11) % 32), 20, 82),
      dataCompleteness: bounded(72 + (seed % 24), 58, 96),
      sourceAgreement: bounded(65 + ((seed + index) % 24), 52, 91),
    },
    priceHistory: history(price * 0.92, price * 0.0025, Math.max(price * 0.025, 0.35)),
    news: [
      news(
        symbol,
        "MarketWatch",
        isSpeculative ? "neutral" : isGrowth ? "positive" : "neutral",
        `${companyNames[symbol] || symbol} added to the AlphaForge research universe`,
        "Seeded universe row. Live price fields update separately when quote data is available."
      ),
    ],
    upcomingDates: ["Next earnings window: provider sync required", "Live data refresh: quote overlay"],
    sourceLinks: [
      { label: "Demo seed universe", url: "https://finance.yahoo.com/", reliability: "demo" },
      { label: "Live quote overlay", url: "https://finance.yahoo.com/lookup/", reliability: "experimental" },
    ],
  };
};

export const researchUniverse = [
  ...rawStocks,
  ...Array.from(new Set(popularSymbols))
    .filter((symbol) => !rawStocks.some((stock) => stock.symbol === symbol))
    .map(createGeneratedStock),
];

export const stocks = researchUniverse
  .map((stock) => scoreStock(stock, marketState))
  .sort((a, b) => b.blendedScore - a.blendedScore);

export const latestNews = researchUniverse.flatMap((stock) => stock.news).slice(0, 10);

export const backtests: BacktestSummary[] = [
  { engine: "Long-term", period: "6 months", winRate: 64, averageReturn: 8.4, maxDrawdown: -9.8, sharpe: 1.18 },
  { engine: "Short-term", period: "1 month", winRate: 58, averageReturn: 3.1, maxDrawdown: -5.7, sharpe: 0.92 },
  { engine: "Long-term", period: "1 year", winRate: 67, averageReturn: 14.6, maxDrawdown: -13.2, sharpe: 1.27 },
];

export const speculativeSignals: SpeculativeSignal[] = [
  {
    symbol: "AMD",
    name: "Advanced Micro Devices",
    theme: "GPU ecosystem",
    marketCap: 260_000_000_000,
    price: 158.7,
    changePercent: 2.4,
    volatility: 57,
    hypeScore: 72,
    fundamentalsScore: 63,
    institutionalInterest: 71,
    dilutionRisk: "Low",
    cashRunwayMonths: 48,
    survivalProbability: 88,
    aiConviction: "High",
    narrative: "AI accelerator share gains",
    narrativeStrength: 76,
    bubbleRisk: 49,
    signal: "High-quality speculative growth, but still valuation and execution sensitive.",
  },
  {
    symbol: "PLTR",
    name: "Palantir Technologies",
    theme: "Defense AI",
    marketCap: 78_000_000_000,
    price: 34.6,
    changePercent: 1.2,
    volatility: 62,
    hypeScore: 86,
    fundamentalsScore: 59,
    institutionalInterest: 67,
    dilutionRisk: "Moderate",
    cashRunwayMonths: 60,
    survivalProbability: 84,
    aiConviction: "High",
    narrative: "Government and enterprise AI adoption",
    narrativeStrength: 82,
    bubbleRisk: 68,
    signal: "Narrative strength is powerful, but hype is running ahead of fundamentals.",
  },
  {
    symbol: "SMCI",
    name: "Super Micro Computer",
    theme: "AI servers",
    marketCap: 48_000_000_000,
    price: 826.4,
    changePercent: 3.1,
    volatility: 74,
    hypeScore: 88,
    fundamentalsScore: 66,
    institutionalInterest: 64,
    dilutionRisk: "Moderate",
    cashRunwayMonths: 28,
    survivalProbability: 73,
    aiConviction: "Speculative",
    narrative: "AI infrastructure buildout",
    narrativeStrength: 89,
    bubbleRisk: 74,
    signal: "Potential infrastructure winner, but volatility and execution risk are elevated.",
  },
  {
    symbol: "SOUN",
    name: "SoundHound AI",
    theme: "Voice AI",
    marketCap: 2_200_000_000,
    price: 5.84,
    changePercent: 4.8,
    volatility: 88,
    hypeScore: 91,
    fundamentalsScore: 34,
    institutionalInterest: 41,
    dilutionRisk: "High",
    cashRunwayMonths: 22,
    survivalProbability: 52,
    aiConviction: "Speculative",
    narrative: "Voice AI adoption",
    narrativeStrength: 71,
    bubbleRisk: 86,
    signal: "Watchlist-only speculative profile; fundamentals do not yet support the hype.",
  },
  {
    symbol: "RGTI",
    name: "Rigetti Computing",
    theme: "Quantum computing",
    marketCap: 510_000_000,
    price: 1.93,
    changePercent: 6.2,
    volatility: 95,
    hypeScore: 84,
    fundamentalsScore: 22,
    institutionalInterest: 28,
    dilutionRisk: "Extreme",
    cashRunwayMonths: 14,
    survivalProbability: 37,
    aiConviction: "Speculative",
    narrative: "Quantum optionality",
    narrativeStrength: 67,
    bubbleRisk: 91,
    signal: "Extremely speculative; cash runway and dilution risk dominate the story.",
  },
  {
    symbol: "IONQ",
    name: "IonQ",
    theme: "Quantum computing",
    marketCap: 2_600_000_000,
    price: 9.92,
    changePercent: 3.9,
    volatility: 83,
    hypeScore: 79,
    fundamentalsScore: 29,
    institutionalInterest: 46,
    dilutionRisk: "High",
    cashRunwayMonths: 30,
    survivalProbability: 57,
    aiConviction: "Speculative",
    narrative: "Commercial quantum milestones",
    narrativeStrength: 73,
    bubbleRisk: 80,
    signal: "Better survival profile than smaller quantum peers, but still early-stage risk.",
  },
];

export const pennyStockSignals: PennyStockSignal[] = [
  {
    symbol: "RGTI",
    name: "Rigetti Computing",
    price: 1.93,
    volumeSpike: 92,
    socialMomentum: 78,
    financingRisk: 88,
    reverseSplitRisk: 61,
    dilutionProbability: 84,
    survivalProbability: 37,
    warning: "Quantum narrative is active, but financing risk is the main limiter.",
  },
  {
    symbol: "QUBT",
    name: "Quantum Computing Inc.",
    price: 0.82,
    volumeSpike: 87,
    socialMomentum: 73,
    financingRisk: 91,
    reverseSplitRisk: 76,
    dilutionProbability: 89,
    survivalProbability: 29,
    warning: "Extremely speculative; reverse-split and dilution probability require prominent warnings.",
  },
  {
    symbol: "BBAI",
    name: "BigBear.ai",
    price: 2.14,
    volumeSpike: 79,
    socialMomentum: 69,
    financingRisk: 74,
    reverseSplitRisk: 43,
    dilutionProbability: 72,
    survivalProbability: 45,
    warning: "Defense AI theme is interesting, but financial quality is not proven.",
  },
];

export const emergingNarratives: EmergingNarrative[] = [
  {
    theme: "AI Infrastructure Boom",
    strength: 88,
    momentum: "Increasing",
    trackedAreas: ["data centers", "power demand", "cooling tech", "networking chips"],
    riskNote: "Capex cycles can reverse quickly if cloud demand slows.",
  },
  {
    theme: "Quantum Computing",
    strength: 73,
    momentum: "Increasing",
    trackedAreas: ["government funding", "research milestones", "commercial pilots"],
    riskNote: "Revenue is early, timelines are long, and dilution risk is common.",
  },
  {
    theme: "Defense AI",
    strength: 81,
    momentum: "Stable",
    trackedAreas: ["contracts", "autonomous systems", "cybersecurity", "edge AI"],
    riskNote: "Procurement cycles and policy headlines can shift momentum.",
  },
  {
    theme: "Nuclear Power Demand",
    strength: 77,
    momentum: "Increasing",
    trackedAreas: ["SMRs", "uranium", "grid capacity", "data-center power"],
    riskNote: "Regulatory timing and project financing remain hard constraints.",
  },
];

export const supplyChainLinks: SupplyChainLink[] = [
  {
    chain: "NVDA -> TSMC -> ASML -> MU",
    theme: "Training chips and memory",
    strength: 91,
    risk: "Export controls and advanced packaging bottlenecks.",
  },
  {
    chain: "AMD -> TSMC -> AMAT -> SK Hynix",
    theme: "Accelerators and HBM",
    strength: 78,
    risk: "Gross margin pressure and supply allocation.",
  },
  {
    chain: "SMCI -> NVDA -> VRT -> ETN",
    theme: "AI servers, cooling, and power",
    strength: 84,
    risk: "Inventory cycles and data-center capex pauses.",
  },
];
