import { scoreStock } from "@/lib/scoring";
import type {
  BacktestSummary,
  EmergingNarrative,
  MarketState,
  NewsItem,
  PennyStockSignal,
  PricePoint,
  RawStockSignal,
  SectorSignal,
  SpeculativeSignal,
  SupplyChainLink,
} from "@/lib/types";

const history = (base: number, drift: number, volatility: number): PricePoint[] =>
  Array.from({ length: 42 }, (_, index) => {
    const wave = Math.sin(index / 3.4) * volatility + Math.cos(index / 6) * volatility * 0.6;
    const close = Number((base + index * drift + wave).toFixed(2));
    const date = new Date(Date.UTC(2026, 3, 1 + index)).toISOString().slice(0, 10);

    return {
      date,
      close,
      volume: Math.round(1_000_000 + Math.abs(wave) * 180_000 + index * 19_000),
    };
  });

const sourceUrls: Record<string, string> = {
  "Analyst desk": "https://finance.yahoo.com/research-hub/",
  Benzinga: "https://www.benzinga.com/",
  "Energy desk": "https://www.eia.gov/",
  FDA: "https://www.fda.gov/",
  "FDA calendar": "https://www.fda.gov/",
  Finnhub: "https://finnhub.io/",
  MarketWatch: "https://www.marketwatch.com/",
  Reuters: "https://www.reuters.com/markets/",
  SEC: "https://www.sec.gov/edgar/search/",
};

const news = (
  symbol: string,
  source: string,
  sentiment: NewsItem["sentiment"],
  title: string,
  summary: string
): NewsItem => ({
  id: `${symbol}-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
  symbol,
  title,
  source,
  url: sourceUrls[source] || "https://finance.yahoo.com/news/",
  sentiment,
  relevance: sentiment === "neutral" ? 62 : 78,
  publishedAt: "2026-05-16T13:20:00.000Z",
  summary,
});

export const marketState: MarketState = {
  regime: "Risk-On",
  mood: "Constructive but not complacent",
  fearGreed: 58,
  fearGreedLabel: "Greed",
  vix: 17.8,
  breadth: 64,
  trendScore: 69,
  macroRisk: 44,
  mostBullishSector: "Semiconductors",
  mostBearishSector: "Consumer Retail",
  updatedAt: "2026-05-16T14:30:00.000Z",
  drivers: [
    "Large-cap earnings revisions are positive.",
    "Credit stress is contained, but rate sensitivity remains relevant.",
    "Market breadth is healthy enough to support selective momentum.",
  ],
  risks: [
    "High-valuation growth names remain sensitive to bond yields.",
    "Geopolitical headline risk can change intraday sentiment quickly.",
    "Crowded AI narratives require stronger evidence before confidence rises.",
  ],
};

export const sectors: SectorSignal[] = [
  { sector: "Semiconductors", relativeStrength: 86, sentiment: 78, flow: 82, label: "Leadership" },
  { sector: "Healthcare", relativeStrength: 73, sentiment: 68, flow: 66, label: "Defensive bid" },
  { sector: "Energy", relativeStrength: 70, sentiment: 61, flow: 74, label: "Macro tailwind" },
  { sector: "Financials", relativeStrength: 62, sentiment: 55, flow: 58, label: "Rate watch" },
  { sector: "Software", relativeStrength: 59, sentiment: 71, flow: 52, label: "Selective" },
  { sector: "Consumer Staples", relativeStrength: 53, sentiment: 49, flow: 60, label: "Stable" },
  { sector: "Industrials", relativeStrength: 50, sentiment: 52, flow: 47, label: "Sideways" },
  { sector: "Consumer Retail", relativeStrength: 38, sentiment: 35, flow: 31, label: "Weak breadth" },
];

export const rawStocks: RawStockSignal[] = [
  {
    symbol: "NVDA",
    name: "NVIDIA",
    sector: "Semiconductors",
    industry: "Accelerated computing",
    marketCap: 3_150_000_000_000,
    price: 132.45,
    changePercent: 1.8,
    metrics: {
      revenueGrowth: 74,
      profitMargin: 56,
      freeCashFlowMargin: 47,
      debtToEquity: 0.25,
      pe: 47,
      forwardPe: 31,
      peg: 1.3,
      priceToSales: 18,
      roe: 72,
      moat: 94,
      consistency: 88,
      epsGrowth: 82,
      earningsSurprise: 78,
      guidanceScore: 86,
      volatility: 48,
      beta: 1.65,
      negativeNewsRisk: 39,
      momentum30d: 82,
      aboveMovingAverages: 91,
      rsiQuality: 68,
      volumeSpike: 72,
      newsSentimentScore: 79,
      breakoutQuality: 76,
      supportQuality: 64,
      stopLossDistance: 9,
      institutionalFlow: 84,
      insiderSignal: 52,
      dataCompleteness: 94,
      sourceAgreement: 83,
    },
    priceHistory: history(116, 0.38, 3.8),
    news: [
      news("NVDA", "Benzinga", "positive", "AI infrastructure demand remains resilient", "Analysts continue to cite data center demand and supply visibility."),
      news("NVDA", "SEC", "neutral", "Quarterly filing highlights export-control risk", "Management flags geopolitical and regulatory risk in core markets."),
    ],
    upcomingDates: ["Earnings window: late May", "Investor conference: June 2026"],
    sourceLinks: [
      { label: "SEC filings", url: "https://www.sec.gov/edgar/search/", reliability: "primary" },
      { label: "Financial Modeling Prep", url: "https://financialmodelingprep.com/", reliability: "licensed" },
    ],
  },
  {
    symbol: "MSFT",
    name: "Microsoft",
    sector: "Software",
    industry: "Cloud platforms",
    marketCap: 3_000_000_000_000,
    price: 431.2,
    changePercent: 0.7,
    dividendYield: 0.7,
    metrics: {
      revenueGrowth: 17,
      profitMargin: 36,
      freeCashFlowMargin: 33,
      debtToEquity: 0.36,
      pe: 34,
      forwardPe: 29,
      peg: 2.1,
      priceToSales: 12,
      roe: 39,
      moat: 91,
      consistency: 92,
      epsGrowth: 21,
      earningsSurprise: 66,
      guidanceScore: 74,
      volatility: 26,
      beta: 0.93,
      negativeNewsRisk: 23,
      momentum30d: 68,
      aboveMovingAverages: 76,
      rsiQuality: 69,
      volumeSpike: 51,
      newsSentimentScore: 72,
      breakoutQuality: 62,
      supportQuality: 76,
      stopLossDistance: 6,
      institutionalFlow: 74,
      insiderSignal: 47,
      dataCompleteness: 96,
      sourceAgreement: 88,
    },
    priceHistory: history(402, 0.55, 5.1),
    news: [
      news("MSFT", "Finnhub", "positive", "Cloud margins stay in focus", "Investors are watching AI infrastructure spending against Azure growth."),
      news("MSFT", "SEC", "neutral", "Capital expenditure commitments rise", "Long-duration AI infrastructure spending remains a key risk variable."),
    ],
    upcomingDates: ["Dividend date: June", "Cloud product event: June 2026"],
    sourceLinks: [
      { label: "SEC filings", url: "https://www.sec.gov/edgar/search/", reliability: "primary" },
      { label: "Alpha Vantage", url: "https://www.alphavantage.co/", reliability: "licensed" },
    ],
  },
  {
    symbol: "LLY",
    name: "Eli Lilly",
    sector: "Healthcare",
    industry: "Pharmaceuticals",
    marketCap: 810_000_000_000,
    price: 842.1,
    changePercent: 1.1,
    metrics: {
      revenueGrowth: 28,
      profitMargin: 24,
      freeCashFlowMargin: 19,
      debtToEquity: 1.35,
      pe: 61,
      forwardPe: 42,
      peg: 1.9,
      priceToSales: 18,
      roe: 58,
      moat: 88,
      consistency: 79,
      epsGrowth: 44,
      earningsSurprise: 72,
      guidanceScore: 82,
      volatility: 34,
      beta: 0.64,
      negativeNewsRisk: 31,
      momentum30d: 71,
      aboveMovingAverages: 78,
      rsiQuality: 62,
      volumeSpike: 67,
      newsSentimentScore: 75,
      breakoutQuality: 69,
      supportQuality: 71,
      stopLossDistance: 8,
      institutionalFlow: 78,
      insiderSignal: 50,
      dataCompleteness: 91,
      sourceAgreement: 81,
    },
    priceHistory: history(776, 1.35, 13),
    news: [
      news("LLY", "MarketWatch", "positive", "Obesity-drug demand remains a growth driver", "Supply expansion and prescription trends support the long-term thesis."),
      news("LLY", "FDA calendar", "neutral", "Pipeline catalysts create event risk", "Upcoming readouts can widen expected move ranges."),
    ],
    upcomingDates: ["FDA calendar: Q3", "Earnings window: early August"],
    sourceLinks: [
      { label: "SEC filings", url: "https://www.sec.gov/edgar/search/", reliability: "primary" },
      { label: "FRED macro series", url: "https://fred.stlouisfed.org/", reliability: "primary" },
    ],
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase",
    sector: "Financials",
    industry: "Money center banks",
    marketCap: 560_000_000_000,
    price: 203.8,
    changePercent: -0.3,
    dividendYield: 2.1,
    metrics: {
      revenueGrowth: 9,
      profitMargin: 31,
      freeCashFlowMargin: 27,
      debtToEquity: 1.7,
      pe: 13,
      forwardPe: 12,
      peg: 1.4,
      priceToSales: 3.4,
      roe: 17,
      moat: 82,
      consistency: 84,
      epsGrowth: 12,
      earningsSurprise: 60,
      guidanceScore: 62,
      volatility: 24,
      beta: 1.08,
      negativeNewsRisk: 34,
      momentum30d: 56,
      aboveMovingAverages: 61,
      rsiQuality: 65,
      volumeSpike: 45,
      newsSentimentScore: 58,
      breakoutQuality: 48,
      supportQuality: 69,
      stopLossDistance: 5,
      institutionalFlow: 65,
      insiderSignal: 55,
      dataCompleteness: 93,
      sourceAgreement: 78,
    },
    priceHistory: history(195, 0.19, 2.8),
    news: [
      news("JPM", "Reuters", "neutral", "Net interest income remains rate sensitive", "Bank quality is solid, but macro sensitivity drives the setup."),
      news("JPM", "SEC", "neutral", "Credit-loss language stays contained", "Credit quality requires monitoring if unemployment trends weaken."),
    ],
    upcomingDates: ["Stress test results: June", "Dividend update: Q3"],
    sourceLinks: [
      { label: "SEC filings", url: "https://www.sec.gov/edgar/search/", reliability: "primary" },
      { label: "FRED rates", url: "https://fred.stlouisfed.org/", reliability: "primary" },
    ],
  },
  {
    symbol: "XOM",
    name: "Exxon Mobil",
    sector: "Energy",
    industry: "Integrated oil and gas",
    marketCap: 515_000_000_000,
    price: 118.5,
    changePercent: 0.5,
    dividendYield: 3.2,
    metrics: {
      revenueGrowth: 7,
      profitMargin: 11,
      freeCashFlowMargin: 14,
      debtToEquity: 0.21,
      pe: 14,
      forwardPe: 13,
      peg: 1.1,
      priceToSales: 1.4,
      roe: 18,
      moat: 76,
      consistency: 68,
      epsGrowth: 9,
      earningsSurprise: 56,
      guidanceScore: 59,
      volatility: 29,
      beta: 0.98,
      negativeNewsRisk: 41,
      momentum30d: 65,
      aboveMovingAverages: 70,
      rsiQuality: 64,
      volumeSpike: 62,
      newsSentimentScore: 54,
      breakoutQuality: 58,
      supportQuality: 67,
      stopLossDistance: 7,
      institutionalFlow: 69,
      insiderSignal: 58,
      dataCompleteness: 90,
      sourceAgreement: 76,
    },
    priceHistory: history(111, 0.18, 2.4),
    news: [
      news("XOM", "Energy desk", "neutral", "Oil risk premium supports energy flows", "Geopolitical risk and supply discipline are driving sector interest."),
      news("XOM", "SEC", "negative", "Commodity exposure keeps earnings cyclical", "Cash flow remains tied to oil and refining margins."),
    ],
    upcomingDates: ["OPEC meeting: June", "Earnings window: late July"],
    sourceLinks: [
      { label: "SEC filings", url: "https://www.sec.gov/edgar/search/", reliability: "primary" },
      { label: "EIA data", url: "https://www.eia.gov/", reliability: "primary" },
    ],
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices",
    sector: "Semiconductors",
    industry: "Data center chips",
    marketCap: 260_000_000_000,
    price: 158.7,
    changePercent: 2.4,
    metrics: {
      revenueGrowth: 23,
      profitMargin: 7,
      freeCashFlowMargin: 13,
      debtToEquity: 0.05,
      pe: 52,
      forwardPe: 28,
      peg: 1.6,
      priceToSales: 9,
      roe: 7,
      moat: 71,
      consistency: 58,
      epsGrowth: 34,
      earningsSurprise: 61,
      guidanceScore: 70,
      volatility: 57,
      beta: 1.82,
      negativeNewsRisk: 45,
      momentum30d: 76,
      aboveMovingAverages: 82,
      rsiQuality: 60,
      volumeSpike: 84,
      newsSentimentScore: 69,
      breakoutQuality: 81,
      supportQuality: 53,
      stopLossDistance: 13,
      institutionalFlow: 71,
      insiderSignal: 45,
      dataCompleteness: 87,
      sourceAgreement: 72,
    },
    priceHistory: history(136, 0.5, 6.6),
    news: [
      news("AMD", "Benzinga", "positive", "AI chip share narrative strengthens", "Momentum improved after data center commentary and volume expansion."),
      news("AMD", "Analyst desk", "neutral", "Competition risk remains central", "Investors still compare gross margins and ecosystem strength against peers."),
    ],
    upcomingDates: ["Product event: June", "Earnings window: July"],
    sourceLinks: [
      { label: "SEC filings", url: "https://www.sec.gov/edgar/search/", reliability: "primary" },
      { label: "Polygon", url: "https://polygon.io/", reliability: "licensed" },
    ],
  },
];

export const stocks = rawStocks
  .map((stock) => scoreStock(stock, marketState))
  .sort((a, b) => b.blendedScore - a.blendedScore);

export const latestNews = rawStocks.flatMap((stock) => stock.news).slice(0, 10);

export const backtests: BacktestSummary[] = [
  { engine: "Long-term", period: "6 months", winRate: 64, averageReturn: 8.4, maxDrawdown: -9.8, sharpe: 1.18 },
  { engine: "Short-term", period: "1 month", winRate: 58, averageReturn: 3.1, maxDrawdown: -5.7, sharpe: 0.92 },
  { engine: "Long-term", period: "1 year", winRate: 67, averageReturn: 14.6, maxDrawdown: -13.2, sharpe: 1.27 },
];

export const speculativeSignals: SpeculativeSignal[] = [
  {
    symbol: "AMD",
    name: "Advanced Micro Devices",
    theme: "GPU ecosystem",
    marketCap: 260_000_000_000,
    price: 158.7,
    changePercent: 2.4,
    volatility: 57,
    hypeScore: 72,
    fundamentalsScore: 63,
    institutionalInterest: 71,
    dilutionRisk: "Low",
    cashRunwayMonths: 48,
    survivalProbability: 88,
    aiConviction: "High",
    narrative: "AI accelerator share gains",
    narrativeStrength: 76,
    bubbleRisk: 49,
    signal: "High-quality speculative growth, but still valuation and execution sensitive.",
  },
  {
    symbol: "PLTR",
    name: "Palantir Technologies",
    theme: "Defense AI",
    marketCap: 78_000_000_000,
    price: 34.6,
    changePercent: 1.2,
    volatility: 62,
    hypeScore: 86,
    fundamentalsScore: 59,
    institutionalInterest: 67,
    dilutionRisk: "Moderate",
    cashRunwayMonths: 60,
    survivalProbability: 84,
    aiConviction: "High",
    narrative: "Government and enterprise AI adoption",
    narrativeStrength: 82,
    bubbleRisk: 68,
    signal: "Narrative strength is powerful, but hype is running ahead of fundamentals.",
  },
  {
    symbol: "SMCI",
    name: "Super Micro Computer",
    theme: "AI servers",
    marketCap: 48_000_000_000,
    price: 826.4,
    changePercent: 3.1,
    volatility: 74,
    hypeScore: 88,
    fundamentalsScore: 66,
    institutionalInterest: 64,
    dilutionRisk: "Moderate",
    cashRunwayMonths: 28,
    survivalProbability: 73,
    aiConviction: "Speculative",
    narrative: "AI infrastructure buildout",
    narrativeStrength: 89,
    bubbleRisk: 74,
    signal: "Potential infrastructure winner, but volatility and execution risk are elevated.",
  },
  {
    symbol: "SOUN",
    name: "SoundHound AI",
    theme: "Voice AI",
    marketCap: 2_200_000_000,
    price: 5.84,
    changePercent: 4.8,
    volatility: 88,
    hypeScore: 91,
    fundamentalsScore: 34,
    institutionalInterest: 41,
    dilutionRisk: "High",
    cashRunwayMonths: 22,
    survivalProbability: 52,
    aiConviction: "Speculative",
    narrative: "Voice AI adoption",
    narrativeStrength: 71,
    bubbleRisk: 86,
    signal: "Watchlist-only speculative profile; fundamentals do not yet support the hype.",
  },
  {
    symbol: "RGTI",
    name: "Rigetti Computing",
    theme: "Quantum computing",
    marketCap: 510_000_000,
    price: 1.93,
    changePercent: 6.2,
    volatility: 95,
    hypeScore: 84,
    fundamentalsScore: 22,
    institutionalInterest: 28,
    dilutionRisk: "Extreme",
    cashRunwayMonths: 14,
    survivalProbability: 37,
    aiConviction: "Speculative",
    narrative: "Quantum optionality",
    narrativeStrength: 67,
    bubbleRisk: 91,
    signal: "Extremely speculative; cash runway and dilution risk dominate the story.",
  },
  {
    symbol: "IONQ",
    name: "IonQ",
    theme: "Quantum computing",
    marketCap: 2_600_000_000,
    price: 9.92,
    changePercent: 3.9,
    volatility: 83,
    hypeScore: 79,
    fundamentalsScore: 29,
    institutionalInterest: 46,
    dilutionRisk: "High",
    cashRunwayMonths: 30,
    survivalProbability: 57,
    aiConviction: "Speculative",
    narrative: "Commercial quantum milestones",
    narrativeStrength: 73,
    bubbleRisk: 80,
    signal: "Better survival profile than smaller quantum peers, but still early-stage risk.",
  },
];

export const pennyStockSignals: PennyStockSignal[] = [
  {
    symbol: "RGTI",
    name: "Rigetti Computing",
    price: 1.93,
    volumeSpike: 92,
    socialMomentum: 78,
    financingRisk: 88,
    reverseSplitRisk: 61,
    dilutionProbability: 84,
    survivalProbability: 37,
    warning: "Quantum narrative is active, but financing risk is the main limiter.",
  },
  {
    symbol: "QUBT",
    name: "Quantum Computing Inc.",
    price: 0.82,
    volumeSpike: 87,
    socialMomentum: 73,
    financingRisk: 91,
    reverseSplitRisk: 76,
    dilutionProbability: 89,
    survivalProbability: 29,
    warning: "Extremely speculative; reverse-split and dilution probability require prominent warnings.",
  },
  {
    symbol: "BBAI",
    name: "BigBear.ai",
    price: 2.14,
    volumeSpike: 79,
    socialMomentum: 69,
    financingRisk: 74,
    reverseSplitRisk: 43,
    dilutionProbability: 72,
    survivalProbability: 45,
    warning: "Defense AI theme is interesting, but financial quality is not proven.",
  },
];

export const emergingNarratives: EmergingNarrative[] = [
  {
    theme: "AI Infrastructure Boom",
    strength: 88,
    momentum: "Increasing",
    trackedAreas: ["data centers", "power demand", "cooling tech", "networking chips"],
    riskNote: "Capex cycles can reverse quickly if cloud demand slows.",
  },
  {
    theme: "Quantum Computing",
    strength: 73,
    momentum: "Increasing",
    trackedAreas: ["government funding", "research milestones", "commercial pilots"],
    riskNote: "Revenue is early, timelines are long, and dilution risk is common.",
  },
  {
    theme: "Defense AI",
    strength: 81,
    momentum: "Stable",
    trackedAreas: ["contracts", "autonomous systems", "cybersecurity", "edge AI"],
    riskNote: "Procurement cycles and policy headlines can shift momentum.",
  },
  {
    theme: "Nuclear Power Demand",
    strength: 77,
    momentum: "Increasing",
    trackedAreas: ["SMRs", "uranium", "grid capacity", "data-center power"],
    riskNote: "Regulatory timing and project financing remain hard constraints.",
  },
];

export const supplyChainLinks: SupplyChainLink[] = [
  {
    chain: "NVDA -> TSMC -> ASML -> MU",
    theme: "Training chips and memory",
    strength: 91,
    risk: "Export controls and advanced packaging bottlenecks.",
  },
  {
    chain: "AMD -> TSMC -> AMAT -> SK Hynix",
    theme: "Accelerators and HBM",
    strength: 78,
    risk: "Gross margin pressure and supply allocation.",
  },
  {
    chain: "SMCI -> NVDA -> VRT -> ETN",
    theme: "AI servers, cooling, and power",
    strength: 84,
    risk: "Inventory cycles and data-center capex pauses.",
  },
];
